Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y bind9
    sudo service bind9 stop

    echo 'options {' | sudo tee -a /etc/bind/named.conf.options
    echo '  directory "/var/cache/bind";' | sudo tee -a /etc/bind/named.conf.options
    echo '  recursion yes;' | sudo tee -a /etc/bind/named.conf.options
    echo '  allow-recursion { any; };' | sudo tee -a /etc/bind/named.conf.options
    echo '};' | sudo tee -a /etc/bind/named.conf.options

    sudo service bind9 start
  SHELL
end
