Vagrant.configure("2") do |config|
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "ubuntu/focal64"
    vm1.vm.network "private_network", type: "dhcp", virtualbox__intnet: true, auto_config: false, dhcp_ipv6: false, mac: "080027123456"
    vm1.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    vm1.vm.provision "shell", path: "./shell.sh"
    vm1.vm.provision "shell", path: "./services/dns/provision.sh"
    vm1.vm.provision "shell", path: "./services/web/provision.sh"
    vm1.vm.provision "shell", path: "./services/ftp/provision.sh"
    vm1.vm.provision "shell", path: "./services/nfs/provision.sh"
  end
end
