Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y apache2

    # Configuração simples para o Apache
    echo "<html><body><h1>Servidor Web Funcionando!</h1></body></html>" | sudo tee /var/www/html/index.html

    sudo systemctl start apache2
  SHELL
end
