Vagrant.configure("2") do |config|
  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "ubuntu/focal64"
    vm2.vm.network "private_network", type: "dhcp", virtualbox__intnet: true, auto_config: false, dhcp_ipv6: false

    vm2.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    vm2.vm.provision "shell", path: "./shell.sh"
  end
end
