Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y nfs-kernel-server

    # Configuração básica para o servidor NFS
    echo "/vagrant *(rw,sync,no_subtree_check)" | sudo tee -a /etc/exports

    sudo exportfs -a
    sudo systemctl restart nfs-kernel-server
  SHELL
end
